# Generated by Django 2.0.7 on 2018-08-26 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0002_firebasetoken_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebasetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firebase_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
