# Generated by Django 2.0.7 on 2018-07-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('dni', models.BigIntegerField(unique=True)),
                ('domicilio', models.CharField(max_length=150)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_nacimiento', models.DateField()),
                ('legajo', models.BigIntegerField(unique=True)),
                ('_promedio', models.FloatField(blank=True, null=True)),
                ('last_promedio_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('asistio', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_promedio', models.FloatField(blank=True, null=True)),
                ('last_promedio_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('dni', models.BigIntegerField(unique=True)),
                ('domicilio', models.CharField(max_length=150)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
