# Generated by Django 2.0.7 on 2018-07-16 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunicados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatariocomunicado',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='destinatarios',
            field=models.ManyToManyField(through='comunicados.DestinatarioComunicado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_emisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
