# Generated by Django 2.0.7 on 2018-07-16 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseVirtual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Clase', max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('nor', 'Clase Virtual'), ('eva', 'Evaluación'), ('esc', 'Evaluación Escrita')], max_length=3)),
                ('publicado', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('tipo', 'descripcion'),
            },
        ),
        migrations.CreateModel(
            name='EjercicioVirtual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ejercicio', models.CharField(choices=[('txt', 'Texto'), ('mch', 'Multiple Choice')], max_length=3)),
                ('puntaje', models.FloatField(blank=True, null=True)),
                ('orden_prioridad', models.IntegerField(blank=True, null=True)),
                ('consigna', models.CharField(max_length=100)),
                ('ayuda', models.TextField(blank=True, null=True)),
                ('explicacion', models.TextField(blank=True, null=True)),
                ('clase_virtual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='clases.ClaseVirtual')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionEjercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100)),
                ('opcion_correcta', models.BooleanField(default=False)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='clases.EjercicioVirtual')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEjercicioVirtual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default=None, null=True)),
                ('puntaje_obtenido', models.FloatField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default=None, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='alumnos.Alumno')),
                ('clase_virtual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='clases.ClaseVirtual')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='clases.EjercicioVirtual')),
                ('opcion_seleccionada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clases.OpcionEjercicio')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_evaluaciones', to='alumnos.Alumno')),
                ('clase_virtual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='clases.ClaseVirtual')),
            ],
        ),
    ]
