# Generated by Django 2.0.7 on 2018-08-08 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_clasevirtual_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasevirtual',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='fecha_correccion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='fecha_notificado',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
