# Generated by Django 2.0.7 on 2018-10-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_auto_20180808_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasevirtual',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
