# Generated by Django 2.0.7 on 2018-10-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0004_auto_20181018_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasevirtual',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
