# Generated by Django 2.0.7 on 2018-10-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0005_auto_20181018_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasevirtual',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
